[features]
seeds = false
[programs.devnet]
nft_marketplace = "4PYm9iCSmNQokAATfDdAsHzQsiXkcCSNTUzQU8MisNTK"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "/home/administrator/my-solana-wallet/my-keypair.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/test.ts"
test-mint = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/test-mint.ts"
test-bid = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/test-bid.ts"
test-sell = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/test-sell.ts"
